const mongoose = require('mongoose');

const tripSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  name: {
    type: String,
    required: true,
  },
  destination: {
    type: String,
    required: true,
  },
  startDate: {
    type: String,
    required: true,
  },
  endDate: {
    type: String,
    required: true,
  },
  travelers: {
    type: String,
  },
  budget: {
    type: String,
  },
  travelStyle: {
    type: String,
  },
  itinerary: {
    type: Array, // Array of JSON objects as generated by Gemini
    default: [],
  },
  chatHistory: {
    type: Array,
    default: [],
  },
  geminiHistory: {
    type: Array,
    default: [],
  },
  hasGenerated: {
    type: Boolean,
    default: true,
  },
  expenses: {
    type: Array, // Array of expense objects: { id, amount, category, description, date }
    default: [],
  }
}, { timestamps: true });

module.exports = mongoose.model('Trip', tripSchema);
